# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='imdbRating',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='date_watched',
            field=models.DateField(blank=True, null=True),
        ),
    ]
