# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0002_remove_episode_siterating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='overview',
            field=models.TextField(default='N/A'),
        ),
    ]
