# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0002_auto_20170402_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episodeName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='seriesName',
            field=models.CharField(max_length=100),
        ),
    ]
