# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0002_auto_20160725_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='imdbRating',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
