# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0003_auto_20160727_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
