# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0004_auto_20160725_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
