# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0006_auto_20160729_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='genre_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.CharField(default='network', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='siteRating',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='userRating',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True),
        ),
    ]
