# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0007_auto_20160811_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
