# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0008_show_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episodeName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
